Repository mathcodes/contentfordevelopers, pull requests merged in 2022-12, with the labels that each got.

#100 Swarnit
  src/components/Card.css
  src/components/Card.jsx
  src/components/Card.scss
  src/components/Contributer.jsx
  src/components/Contributer.scss
  src/components/ui/card/PlatformCard.jsx
  src/components/ui/card/PlatformCard.scss
  src/pages/Homepage.jsx
  src/pages/Homepage.scss
Labels: documentation, duplicate, enhancement

#104 Change hex color codes to lowercase
  src/components/Card.css
  src/components/Card.css.map
  src/components/Contributer.css
  src/components/Contributer.css.map
  src/components/Footer.css
  src/components/Footer.css.map
  src/components/Navbar.css
  src/components/Navbar.css.map
  src/components/Navbar.scss
  src/components/ui/card/PlatformCard.css
  src/components/ui/card/PlatformCard.css.map
  src/components/ui/footer/Footer.css
  src/components/ui/footer/Footer.css.map
  src/components/ui/header/Header.css
  src/components/ui/header/Header.css.map
  src/pages/Homepage.css
  src/pages/Homepage.css.map
  src/pages/Homepage.scss
  src/sass/main.css
  src/sass/main.css.map
Labels: syntax and organization

#114 UI description styling
  src/pages/Homepage.scss
Labels: enhancement

#115 enhancement: render contributors list through json
  src/components/Contributer.jsx
  src/components/Contributer.scss
  src/db.js
  src/pages/Homepage.jsx
Labels: enhancement

#125 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, urgent
